debug=true

templates="./templates/"

[database]
url = "life-tracker.db"
migration = "./migrations/"


[gpt]
url="https://api.openai.com/v1/chat/completions"
api_key="YOUR_KEY_HERE"
max_tokens=500
model="gpt-4o-mini"
temperature=0.7

[web_config]
host="localhost"
port="8080"
context_path = "/tracker"
login_url = "/tracker/app/login"
cookie_key = "SECRETKAJSDKAJSDFSECRETKAJSDKAJSDFSECRETKAJSDKAJSDFSECRETKAJSDKAJSDFSECRETKAJSDKAJSDFSECRETKAJSDKAJSDFSECRETKAJSDKAJSDFSECRETKAJSDKAJSDFSECRETKAJSDKAJSDFSECRETKAJSDKAJSDFSECRETKAJSDKAJSDFSECRETKAJSDKAJSDFSECRETKAJSDKAJSDFSECRETKAJSDKAJSDFSECRETKAJSDKAJSDFSECRETKAJSDKAJSDFSECRETKAJSDKAJSDF"

