DROP TABLE IF EXISTS project_goals;
DROP TABLE IF EXISTS goals;
DROP TABLE IF EXISTS projects;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS tasks;
DROP TABLE IF EXISTS daily_todos;
DROP TABLE IF EXISTS rewards;